const targets = {
    'https://vigilantcitizen.com': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://protiprudu.org': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://biblik.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://orgo-net.blogspot.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://aeronet.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://conspi.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://nwoo.org': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://geneticka-vakcina.com': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://arfa.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://exopolitika.cz': {number_of_requests: 0, number_of_errored_responses: 0},

    'https://badatel.net': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://czechfreepress.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://qanon.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://zemavek.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://stratenaeuropa.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://bnw-nwo.wz.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://protiprud.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://protiproud.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://blokprotiislamizaci.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://afinabul.blog.cz': {number_of_requests: 0, number_of_errored_responses: 0},

    'https://prvopodstata.com': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://stalo-se.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://slobodavockovani.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://magnificat.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://nekorektni-tv.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://veksvetla.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://sho.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://tadesco.org': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://nadhlad.com': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://pravdive.eu': {number_of_requests: 0, number_of_errored_responses: 0},

    'https://bezpolitickekorektnosti.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://freeglobe.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://stop5g.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://svobodnenoviny.eu': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://vedomec.com': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://anti-illuminati.wbl.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://leva-net.webnode.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://vlasteneckenoviny.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://novarepublika.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://rukojmi.cz': {number_of_requests: 0, number_of_errored_responses: 0},

    'https://rozhladna.org': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://yournewswire.com': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://kralicianora.org': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://slobodnyvysielac.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://ezopress.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://prekladyodlesa.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://pokec24.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://obcianskytribunal.sk': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://infowars.cz': {number_of_requests: 0, number_of_errored_responses: 0},
    'https://idemvolit.sk': {number_of_requests: 0, number_of_errored_responses: 0},

// 'https://tadesco.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://eurasia24.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://nemesis.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://euronoviny.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://zahadnysvet.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://dobajedu.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://tartaria.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://energieupramene.blogspot.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://planetajednoduchost.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://dostojneslovensko.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ac24.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://informace.top': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://petrabostlova.wordpress.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://alternativnimagazin.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://isstras.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://infokuryr.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://zvtv.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://cz24.news': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://voxpopuliblog.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://prehladsprav.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://picuscapital.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://suenee.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://megazine.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://je-to-inak.livejournal.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://naturalnews.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://necenzurovane.net': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://priznakytransformace.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://nadlani.org': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://mysteria.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://freedomeurope.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://lifenews.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://samvojakvpoli.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://otevrisvoumysl.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://naseveru.org': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://eurabia.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://euportal.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://euserver.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://proevropu.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://cestyksobe.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ceskoaktualne.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://pravyprostor.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://podtatransky-kurier.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://sk.news-front.info': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://kulturblog.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://karolinaloskotova.blog.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://nejhorsi.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://osud.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ers.blog.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://infovojna.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://rudovasky.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://tydenikobcanskepravo.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://procproto.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://bajecnezeny.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://casopis-sifra.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://svetkolemnas.info': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://vipnoviny.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://kanal22.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://poockovani.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://inenoviny.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ceskavec.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://freepub.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://dt24.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://zdraveforum.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://rizikaockovania.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://slovanskenoviny.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://desitka.org': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://radyzdravie.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://skrytapravda.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://priezor.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://panobcan.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://slobodnyvyber.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://nazorobcana.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://silavedomia.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://stopislam.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://badatelia.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://zvedavec.org': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://cz.sputniknews.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://southfront.org': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://nejvic-info.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://euroasie.info': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://wmmagazin.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://wertyzreport.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://e-republika.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://obcansky-tydenik.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://cbreurope.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://cestacloveka.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://mcaris.net': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://paratdnes.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://venuska.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://biosferaklub.info': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://medzicas.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://gloria.tv': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://otvoroci.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://extraplus.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://lajkit.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://bajecnezdravie.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://radyprezdravie.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://radyprezeny.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://eurorespekt.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://faktyadokazy.cc': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://mocvedomi.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://datel.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://breitbart.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://drsne.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://slovenskeslovo.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://domacaliecba.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://themindunleashed.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://alatyr.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://slovinfos.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://dennik-dnes.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://magazinslovensko.online': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://reformy.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://aktuality24.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://legalizuj.to': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://narodninoviny.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://fresher.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://radynadzlato.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://outsidermedia.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://arindrexler.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://lucasperny.blog.pravda.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ceskozdrave.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://odbornakomisia.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://eportal.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://elektrosmog.voxo.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://politickemimovladky.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://dolezite.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://napalete.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://vylectese.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://bajecnylekar.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://christianitas.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://magazin1.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://jenona.tiscali.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://zpravodaj24.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://rozhlady.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://woman.tiscali.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://meapatria.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://kupredudominulosti.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ipribeh.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://slovakexportregister.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://ozonyx.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://sknews.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://armadnymagazin.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://weeks.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://prvnizpravy.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://davdva.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://mimoriadnespravy.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://resso.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://somzena.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://vitalitis.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://stredoevropan.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://medicalcentrum.eu': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://spravodaj.net': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://withform.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://trendweb.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://hrot.info': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://precitaj.si': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://babickinerady.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://svobodnymonitor.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://bajecnylekar.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://parlamentne-volby-2016.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://pravda24.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://farmazdravi.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://presstv.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://zlapanda.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://eurodenik.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://onlineslecna.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://bajecnyzivot.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://dennikpolitika.sk': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://prosvet.cz': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://halonoviny.com': {number_of_requests: 0, number_of_errored_responses: 0},
// 'https://epochtimes.cz': {number_of_requests: 0, number_of_errored_responses: 0},

};
